### ISSUE TITLE
[Japanese] translate new guides

### ISSUE THREAD

**Issue by debs-obrien** [nuxt/nuxtjs.org#544]
New guides section needs to be translated. 

See the readMe for info on how to translate our site: https://github.com/nuxt/nuxtjs.org

Feel free to just take one page and submit a pr. make sure you also tick the box in the list below. Or take on the whole project and just create a draft pr and we will merge it when it is finished.

i18n configuration

- [x]  i18n file （ #1393 ）
- [x]  i18n block on nuxt.config （ https://github.com/nuxt/nuxtjs.org/pull/407 ）

📝 guides -> components glossary

<details><summary>Done</summary>

- [x]  pages-fetch.md （ #807 ）
- [x]  pages-head.md （ #814 ）
- [x]  pages-key.md （ #823 ）
- [x]  pages-layout.md （ #824 ）
- [x]  pages-loading.md （ #838 ）
- [x]  pages-middleware.md （ vuejs-jp#102 ）
- [x]  pages-scrolltotop.md （ vuejs-jp#119 ）
- [x]  pages-transition.md （ vuejs-jp#103 ）
- [x]  pages-validate.md （ vuejs-jp#121 ）
- [x]  pages-watchquery.md （ vuejs-jp#104 ）
</details>

📝 guides -> concepts

<details><summary>Done</summary>

- [x]  context-helpers.md （ vuejs-jp#91 ）
- [x]  nuxt-lifecycle.md （ vuejs-jp#129 ）
- [x]  server-side-rendering.md （ vuejs-jp#111 ）
- [x]  static-site-generation.md （ vuejs-jp#131 ）
- [x]  view.md （ vuejs-jp#132 ）

</details>

📝 guides -> configuration glossary
 
<details><summary>Done</summary>

- [x] configuration-build.md（ #730 ）
- [x]  configuration-generate.md （ #842  ）
- [x]  configuration-render.md （ vuejs-jp#107 ）
- [x]  configuration-server.md （ vuejs-jp#142 ）
- [x]  configuration-telemetry.md （ vuejs-jp#134 ）
- [x]  configuration-router.md （ vuejs-jp#140 ）
- [x]  configuration-server-middleware.md （ vuejs-jp#136 ）
- [x]  configuration-transition.md （ vuejs-jp#139 ）
- [x]  configuration-builddir.md （ #731  ）
- [x]  configuration-cli.md （ #732 ）
- [x]  configuration-components.md （ #733 ）
- [x]  configuration-css.md （ #734 ）
- [x]  configuration-dev.md （ #820 ）
- [x]  configuration-dir.md （ #821 ）
- [x]  configuration-env.md （ #827 ）
- [x]  configuration-extend-plugins.md （ #822 ）
- [x]  configuration-global-name.md （ #843 ）
- [x]  configuration-head.md （ #826 ）
- [x]  configuration-hooks.md （ #863 ）
- [x]  configuration-ignore.md （ #841 ）
- [x]  configuration-loading.md （ #862 ）
- [x]  configuration-loading-indicator.md （ #861 ）
- [x]  configuration-mode.md （ #860 ）
- [x]  configuration-modern.md （ #859 ）
- [x]  configuration-modules.md （ vuejs-jp#113 ）
- [x]  configuration-modulesdir.md （ vuejs-jp#135 ）
- [x]  configuration-plugins.md （ vuejs-jp#138 ）
- [x]  configuration-rootdir.md （ vuejs-jp#133 ）
- [x]  configuration-runtime-config.md （ vuejs-jp#141 ）
- [x]  configuration-srcdir.md （ vuejs-jp#106 ）
- [x]  configuration-ssr.md （ #995 ）
- [x]  configuration-target.md （ vuejs-jp#112 ）
- [x]  configuration-vue-config.md （ vuejs-jp#137 ）
- [x]  configuration-watch.md （ vuejs-jp#116 ）
- [x]  configuration-watchers.md （ vuejs-jp#114 ）

</details>

📝 guides -> directory structure

- [x]  assets.md （ vuejs-jp#115 ）
- [x]  components.md （ vuejs-jp#108 ）
- [x]  content.md （ vuejs-jp#122 ）
- [x]  dist.md （ vuejs-jp#124 ）
- [x]  layouts.md （ vuejs-jp#105 ）
- [x]  middleware.md （ vuejs-jp#145 ）
- [x]  modules.md （ vuejs-jp#144 ）
- [x]  nuxt.md （ vuejs-jp#125 ）
- [x]  nuxt-config.md （ vuejs-jp#123 ）
- [x]  pages.md （ vuejs-jp#143 ）
- [x]  plugins.md （ vuejs-jp#109 ）
- [x]  static.md （ vuejs-jp#147 ）
- [x]  store.md （ vuejs-jp#146 ）

📝 guides -> features

<details><summary>Done</summary>

- [x]  configuration.md（ #755 ）
- [x]  data-fetching.md（ #891 ）
- [x]  deployment-targets.md （#617 ）
- [x]  file-system-routing.md（ #765 ）
- [x]  live-preview.md （ #618 ）
- [x]  loading.md （ #750 ）
- [x]  meta-tags-seo.md （ #714 ）
- [x]  nuxt-components.md （ #770 ）
- [x]  rendering-modes.md（ #616 ）
- [x]  transitions.md（ #619 ）

</details>

📝 guides -> get-started

<details><summary>Done</summary>

- [x] conclusion.md （ #693 ）
- [x] directory-structure.md （ #729 ）
- [x] installation.md （ #667 ）
- [x] routing.md （ #612 ）
- [x] upgrading.md （ #666 ）
- [x] commands.md （ vuejs-jp#130 ）

</details>

📝 guides -> internals glossary

<details><summary>Done</summary>

- [x]  $nuxt.md （ vuejs-jp#110 ）
- [x]  context.md （ vuejs-jp#117 ）
- [x]  internals.md （ vuejs-jp#149 ）
- [x]  internals-builder.md （ vuejs-jp#148 ）
- [x]  internals-generator.md （ vuejs-jp#150 ）
- [x]  internals-module-container.md （ vuejs-jp#151 ）
- [x]  internals-nuxt.md （ vuejs-jp#153 ）
- [x]  internals-renderer.md （ vuejs-jp#155 ）
- [x]  nuxt.md （ vuejs-jp#154 ）
- [x]  nuxt-render.md （ vuejs-jp#118 ）
- [x]  nuxt-render-and-get-window.md （ vuejs-jp#120 ）
- [x]  nuxt-render-route.md （ vuejs-jp#152 ）

</details>

**Comment by debs-obrien** [comment]
@aytdm if you have time or can ping any of the amazing Japanese who have previously helped with our docs

**Comment by aytdm** [comment]
@debs-obrien Thanks. I'd like to move forward with the translation with members of the Vue.js Japan user group (@inouetakuya, @53able and @aytdm). There are many other untranslated documents in addition to the `guides`, so we'll proceed step by step💪

**Comment by debs-obrien** [comment]
fantastic. feel free to add a task list or however you would prefer to do it. The guide and api section will soon be removed once the guides section is translated. Examples, faq and resources will be moved to a new section and will be improved. We are working on this at present but it will be a while before released. Guides would be the best place to start in my opinion as this is the new en version.

**Comment by aytdm** [comment]
Thank you for the helpful information. If `guide` and `api` section will be removed, then as you say, `guides` should be priority to translate.

This is off the topic, but could you give us the access rights to review and merge PR? Similarly to `nuxt/docs`, we would like to promote the translation of Japanese documents under the leadership of the Vue.js Japan user group. (We'd like to release a document that has been reviewed.)

**Comment by debs-obrien** [comment]
@pi0 is there a way to give access to review and merge for only the content/ja part of the website or how can we best work so that the Vue.js Japan team can merge without me having to review.

**Comment by aytdm** [comment]
@pi0 @debs-obrien How about using [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners)? I think this way can be restrict access right subject to directory.

**Comment by debs-obrien** [comment]
Very interesting. Looks great. Will leave @pi0 to decide on if it makes sense to setup. Until then feel free to just work away and add me as a reviewer when ready to merge.

**Comment by aytdm** [comment]
Thank you ☺️

**Comment by debs-obrien** [comment]
Hey I have created labels to make it easier to also filter the prs. If you can go through any of them and let me know which ones are ready for merging that would be great. I will not merge until I hear from you @aytdm. Just add my name to a comment and I will receive an alert and will merge. Thanks for the great work. Good to see so much work being done on the Japanese version 😊
https://github.com/nuxt/nuxtjs.org/pulls?q=is%3Aopen+is%3Apr+label%3Ajapanese

**Comment by aytdm** [comment]
@debs-obrien I got it. Thanks for your consideration ☺️

**Comment by aytdm** [comment]
We've all done 🙌
